name: Deploy React App
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm ci
      - name: Test applications
        run: npm run test
      - name: Lint applications
        run: npm run lint  
      - name: Build applications
        run: npm run build
      - name: Deploy
        run: echo Deploying  
  